### ISSUE TITLE
 SHA_CBLOCK redefined in ngx_http_sticky_misc.c:23

### ISSUE THREAD

**Issue by mgaydash** [Refinitiv/nginx-sticky-module-ng#11]
When building, I encounter the error `ngx_http_sticky_misc.c:23: error: "SHA_CBLOCK" redefined [-Werror]`. This seems to be happening because of the redefinition in the line referenced:
https://github.com/Refinitiv/nginx-sticky-module-ng/blob/6fe17af5a07aa6782d0080d4255b0f4a9de18125/ngx_http_sticky_misc.c#L27

**Comment by accedic** [comment]
@mgaydash did you manage to solve this? if so what was the fix? i know its been a year but maybe you remember.

**Comment by mgaydash** [comment]
@accedic Unfortunately, I don't have a technical solution to offer. I just built a previous version or the module that doesn't have the 'redefined' problem.

**Comment by NobleTuna** [comment]
@accedic @mgaydash 

I had the same issue when compiling with openssl-1.1.1s module.
Both are defined as 64

`grep 'define SHA_CBLOCK' -r ./
./openssl-1.1.1s/include/openssl/sha.h:# define SHA_CBLOCK      (SHA_LBLOCK*4)/* SHA treats input data as a
./openssl-1.1.1s/.openssl/include/openssl/sha.h:# define SHA_CBLOCK      (SHA_LBLOCK*4)/* SHA treats input data as a
./nginx-sticky-module-ng/ngx_http_sticky_misc.c:#define SHA_CBLOCK 64
./nginx-sticky-module-ng/ngx_http_sticky_misc.c:#define SHA_CBLOCK 64

grep SHA_LBLOCK -r ./
...
./openssl-1.1.1s/include/openssl/sha.h:# define SHA_LBLOCK      16`

So I deleted 
./nginx-sticky-module-ng/ngx_http_sticky_misc.c:#define SHA_CBLOCK 64
and compiled successfully.
