### ISSUE TITLE
why you copy the project from other people? 

### ISSUE THREAD

**Issue by dmeniche** [Refinitiv/nginx-sticky-module-ng#7]
origin source : 
GitHub - Refinitiv/nginx-sticky-module-ng: Fork of https://bitbucket.org/nginx-goodies/nginx-sticky-module-ng community

pls, tell me why ?

**Comment by steamboatid** [comment]
it's fork, not a copy

**Comment by JonathanHuot** [comment]
As explained by @steamboatid and also in the About github section, it is a fork. Note the bitbucket repo is abandonned, so it is expected to see fork there and there. If you want to maintain an official version of the project, please do it.
